### PR TITLE
Footnote 1 redundant

### PR DESCRIPTION
**Pull request by proftomwbell**
Because footnote 1 was not conveying useful info, I deleted it in the base version and re-numbered the other notes accordingly.  Not being sure you would otherwise get notice of that minor change, I figured a pull request might serve.

### CODE REVIEW

**Comment by macterra** [comment]
I don't think you want to be re-merging the 6 commits from my branch. Let me know if you need assistance creating a new branch from master for your changes.

**Comment by macterra** [comment]
OK to close this one without merging?

**Comment by proftomwbell** [comment]
Have at it, please.  Sorry for the delayed response.

**Comment by macterra** [comment]
OK closing this PR without merging under the assumption that the change under review was [already committed](https://github.com/proftomwbell/Ulex/commit/867c3446e6127de3ffb008fd3f089d1cde55c8e2)

**Pull request closed without merging**
